//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountChart
    {
        public int id { get; set; }
        public string accountTypeId { get; set; }
        public string accountCode { get; set; }
        public string accountName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> editAble { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string OwnerId { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
