//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddIncome
    {
        public int Id { get; set; }
        public string OwnerId { get; set; }
        public string PropertyManagerId { get; set; }
        public string LocationId { get; set; }
        public string UnitId { get; set; }
        public string ResidentTenantName { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> EnterAmountBeingPaid { get; set; }
        public string AccountType { get; set; }
        public string AccountName { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string RoutingNo { get; set; }
        public string AccountNo { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> CashReceiptDate { get; set; }
        public string CashReceiptFrom { get; set; }
        public string CashReceiptFor { get; set; }
        public Nullable<int> PaymentHistoryId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
