//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string TypeOfContact { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsSentEmail { get; set; }
        public Nullable<bool> IsLocation { get; set; }
        public Nullable<bool> IsEmergencyContact { get; set; }
        public string EmergencyContact { get; set; }
        public string LocationId { get; set; }
        public string OwnerId { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
    }
}
