//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string LocationType { get; set; }
        public string Serial { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string OwnerId { get; set; }
        public string PropertyManagerId { get; set; }
        public string LocationName { get; set; }
        public string SchoolDistract { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<decimal> Lots { get; set; }
        public Nullable<decimal> TotalSize { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> SchoolTax { get; set; }
        public Nullable<decimal> PropertyTax { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsBackgroundCheck { get; set; }
        public Nullable<bool> IsCondoFee { get; set; }
        public Nullable<bool> IsRentMonthly { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Logo { get; set; }
    }
}
