//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordInvoice
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string BillNumber { get; set; }
        public string OwnerId { get; set; }
        public string BillTo { get; set; }
        public string PersonType { get; set; }
        public string PersonCompany { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ContactName { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
