//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentialUnit
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string UnitName { get; set; }
        public string UnitType { get; set; }
        public string SpecialStatements { get; set; }
        public string OwnerId { get; set; }
        public string PropertyManagerSerialId { get; set; }
        public string LocationSerialId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsBackgroundCheck { get; set; }
        public Nullable<bool> IsCondoFee { get; set; }
        public Nullable<bool> IsRentMonthly { get; set; }
        public string Logo { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ShortWebUrl { get; set; }
        public string ImageType { get; set; }
    
        public virtual ResidentialUnit ResidentialUnit1 { get; set; }
        public virtual ResidentialUnit ResidentialUnit2 { get; set; }
    }
}
