//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential_Tenant_Add_Step2_Page2_CreditHistory_New
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ResidentialUnitSerialId { get; set; }
        public string SavingsAcc_BankName_1 { get; set; }
        public string SavingsAcc_Balance_1 { get; set; }
        public string SavingsAcc_BankName_2 { get; set; }
        public string SavingsAcc_Balance_2 { get; set; }
        public string CheckingAcc_BankName_1 { get; set; }
        public string CheckingAcc_Balance_1 { get; set; }
        public string CheckingAcc_BankName_2 { get; set; }
        public string CheckingAcc_Balance_2 { get; set; }
        public string All_Credit_Cards_BankName { get; set; }
        public string All_Credit_Cards_Balance { get; set; }
        public string Auto_Credit_Cards_Balance { get; set; }
        public string Auto_Loan_BankName { get; set; }
        public string Other_BankName { get; set; }
        public string Other_Balance { get; set; }
    }
}
