//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential_Tenant_Add_Step2_Page3_GeneralInformation
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ResidentialUnitSerialId { get; set; }
        public string LateRentNotice { get; set; }
        public string PropertySmoke { get; set; }
        public string RentingFrom { get; set; }
        public string Bankruptcy { get; set; }
        public string MoveIn { get; set; }
        public string Felony { get; set; }
        public string Eviction { get; set; }
        public string EvictionWhen { get; set; }
        public string PetsDetails { get; set; }
        public string Reoccurringproblems { get; set; }
        public string ReoccurringProblemsWhen { get; set; }
        public string MovingReason { get; set; }
        public string VerifiableIncome { get; set; }
        public string LoanHelpingPersons { get; set; }
        public string LawsuitParty { get; set; }
        public string LawsuitPartyReason { get; set; }
        public string CriminalBackground { get; set; }
        public string CriminalBackgroundReason { get; set; }
        public string AboutApartment { get; set; }
        public string ApartmentRefererPersonDetails { get; set; }
        public string BankruptcyDate { get; set; }
    }
}
