//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential_Tenant_Add_Step2_ResidenceHistory
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ResidentialUnitSerialId { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StateName { get; set; }
        public string ZipCode { get; set; }
        public Nullable<decimal> MonthlyAmount { get; set; }
        public string OwnerManagerName { get; set; }
        public string OwnerManagerPhone { get; set; }
        public string ReasonForLeaving { get; set; }
        public string IsRentPaidFull { get; set; }
        public string DidGiveNotice { get; set; }
        public string AskToMove { get; set; }
        public string UtilizesBilled { get; set; }
        public string LivedFromDate { get; set; }
        public string LivedTo { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
    }
}
