//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential_Tenant_Add_Step2_Page2_PeopleStayingUnit
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ResidentialUnitSerialId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Relationship { get; set; }
        public string RelationshipName { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
