//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential_Tenant_App_Step2_AgreementNameOf
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ResidentialUnitSerialId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string AliasName { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string EmailAddress { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string DriversLicenseNo { get; set; }
        public string LicenceState { get; set; }
        public string SocialSecurityNo { get; set; }
        public string RelationShip { get; set; }
        public string Other { get; set; }
        public string Birthday { get; set; }
        public Nullable<int> NoOfPeopleLivingUnit { get; set; }
        public Nullable<int> NoOfPeopleLiving18 { get; set; }
    }
}
