//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentialUnitSpecs
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ResidentialUnitSerialId { get; set; }
        public Nullable<decimal> UnitSize { get; set; }
        public Nullable<int> UnitNumberFloors { get; set; }
        public Nullable<int> UnitNumberOfBaths { get; set; }
        public Nullable<decimal> UnitMonthlyRent { get; set; }
        public Nullable<int> UnitLotSize { get; set; }
        public Nullable<int> UnitNumberBedrooms { get; set; }
        public Nullable<decimal> UnitApplicationFee { get; set; }
        public Nullable<bool> IsUnitIncludeCardProcessCharge { get; set; }
        public string UnitAgentName { get; set; }
        public string UnitAgentPhone { get; set; }
        public string UnitBrokerName { get; set; }
        public string UnitSpecialStatements { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UnitBrokerPhone { get; set; }
        public Nullable<decimal> AdvertisedFee { get; set; }
    }
}
