//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantOnlineFee
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string UnitId { get; set; }
        public string TenantId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> PaymentHistoryId { get; set; }
        public string AccountName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string RoutingNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
