//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SecurityLevel { get; set; }
        public string Location { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseLocation { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> CanLogin { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string OwnerId { get; set; }
        public string LocationId { get; set; }
        public Nullable<bool> HasSystemInfo { get; set; }
        public Nullable<bool> HasOwnerProfile { get; set; }
        public Nullable<bool> HasPropertyManagerProfile { get; set; }
        public Nullable<bool> HasUserProfile { get; set; }
        public Nullable<bool> HasContactProfile { get; set; }
        public Nullable<bool> HasPropertyLocation { get; set; }
        public Nullable<bool> HasPropertyUnit { get; set; }
        public Nullable<bool> HasVendorProfile { get; set; }
        public Nullable<bool> HasLedgerCode { get; set; }
        public Nullable<bool> HasCompletedFullProfile { get; set; }
        public Nullable<bool> HasFinishedTenantImport { get; set; }
        public Nullable<bool> HasAccountSystem { get; set; }
        public Nullable<bool> HasDocuments { get; set; }
    }
}
